// <auto-generated />
using System;
using DbPoc.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbPoc.Persistence.Migrations
{
    [DbContext(typeof(DbPocDbContext))]
    [Migration("20190108161227_product+")]
    partial class product
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbPoc.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("NetPrice");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("image");

                    b.Property<decimal>("Quantity");

                    b.Property<int>("Unit");

                    b.Property<decimal>("Vat");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tej",
                            NetPrice = 230m,
                            Quantity = 26m,
                            Unit = 3,
                            Vat = 5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kenyér",
                            NetPrice = 230m,
                            Quantity = 42m,
                            Unit = 2,
                            Vat = 5m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Herz szalámi",
                            NetPrice = 230m,
                            Quantity = 55m,
                            Unit = 1,
                            Vat = 5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
