// <auto-generated />
using System;
using DbPoc.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbPoc.Persistence.Migrations
{
    [DbContext(typeof(DbPocDbContext))]
    [Migration("20190114133608_temporal table computed")]
    partial class temporaltablecomputed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbPoc.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Name");

                    b.Property<decimal>("NetPrice");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("image");

                    b.Property<decimal>("Quantity");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Unit");

                    b.Property<decimal>("Vat");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tej",
                            NetPrice = 230m,
                            Quantity = 26m,
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = 3,
                            Vat = 5m
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kenyér",
                            NetPrice = 230m,
                            Quantity = 42m,
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = 2,
                            Vat = 5m
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Herz szalámi",
                            NetPrice = 230m,
                            Quantity = 55m,
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unit = 1,
                            Vat = 5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
