// <auto-generated />
using System;
using DbPoc.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbPoc.Persistence.Migrations
{
    [DbContext(typeof(DbPocDbContext))]
    [Migration("20190121103502_create temporal table")]
    partial class createtemporaltable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbPoc.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("NetPrice");

                    b.Property<int?>("ParentId");

                    b.Property<int>("Unit");

                    b.Property<decimal>("Vat");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tej",
                            NetPrice = 230m,
                            Unit = 3,
                            Vat = 5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kenyér",
                            NetPrice = 230m,
                            Unit = 2,
                            Vat = 5m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Herz szalámi",
                            NetPrice = 230m,
                            Unit = 1,
                            Vat = 5m
                        });
                });

            modelBuilder.Entity("DbPoc.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComponentProductId");

                    b.Property<decimal>("ComponentQuantity");

                    b.Property<int?>("CompositeProductId");

                    b.HasKey("Id");

                    b.HasIndex("ComponentProductId");

                    b.HasIndex("CompositeProductId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DbPoc.Domain.Entities.Product", b =>
                {
                    b.HasOne("DbPoc.Domain.Entities.Product", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DbPoc.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("DbPoc.Domain.Entities.Product", "ComponentProduct")
                        .WithMany("CompositeProducts")
                        .HasForeignKey("ComponentProductId");

                    b.HasOne("DbPoc.Domain.Entities.Product", "CompositeProduct")
                        .WithMany("ComponentProducts")
                        .HasForeignKey("CompositeProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
